#!/usr/bin/env bun

import { Script } from "@mimo-ai/script"
import fs from "fs"
import path from "path"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

await import("./generate.ts")

// Generate src/ext/_manifest.ts (same logic as build.ts)
const extDir = path.join(dir, "src", "ext")
if (fs.existsSync(extDir)) {
  const extFiles = fs.readdirSync(extDir)
    .filter((f) => f.endsWith(".ts") && !f.endsWith(".d.ts") && f !== "_manifest.ts")
    .sort()
  const manifestImports = extFiles.map((f, i) => `import * as m${i} from "./${f.replace(/\.ts$/, "")}"`).join("\n")
  const manifestEntries = extFiles.map((f, i) => `  ["${f.replace(/\.ts$/, "")}", m${i}],`).join("\n")
  fs.writeFileSync(
    path.join(extDir, "_manifest.ts"),
    `// Generated by script/build-node.ts. Do not edit.\n${manifestImports}\nexport const modules: Record<string, Record<string, unknown>> = Object.fromEntries([\n${manifestEntries}\n])\n`,
  )
  if (extFiles.length) console.log(`Generated ext/_manifest.ts (${extFiles.length} modules)`)
}

// Load migrations from migration directories
const migrationDirs = (
  await fs.promises.readdir(path.join(dir, "migration"), {
    withFileTypes: true,
  })
)
  .filter((entry) => entry.isDirectory() && /^\d{4}\d{2}\d{2}\d{2}\d{2}\d{2}/.test(entry.name))
  .map((entry) => entry.name)
  .sort()

const migrations = await Promise.all(
  migrationDirs.map(async (name) => {
    const file = path.join(dir, "migration", name, "migration.sql")
    const sql = await Bun.file(file).text()
    const match = /^(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})/.exec(name)
    const timestamp = match
      ? Date.UTC(
          Number(match[1]),
          Number(match[2]) - 1,
          Number(match[3]),
          Number(match[4]),
          Number(match[5]),
          Number(match[6]),
        )
      : 0
    return { sql, timestamp, name }
  }),
)
console.log(`Loaded ${migrations.length} migrations`)

await Bun.build({
  target: "node",
  entrypoints: ["./src/node.ts"],
  outdir: "./dist/node",
  format: "esm",
  sourcemap: "linked",
  external: ["jsonc-parser", "@lydell/node-pty"],
  define: {
    OPENCODE_MIGRATIONS: JSON.stringify(migrations),
    MIMOCODE_CHANNEL: `'${Script.channel}'`,
  },
  files: {
    "opencode-web-ui.gen.ts": "",
  },
})

console.log("Build complete")
